// Per-dialect SQL keyword and function lists used by Monaco autocompletion.
// Shared/common lists are exported directly; dialect-specific ones are grouped
// under dialect objects so callers can pick by capabilities().dialect.

// ── Shared DML / DDL keywords (all engines) ──────────────────────────────────

const COMMON_KEYWORDS = [
  'SELECT','FROM','WHERE','AND','OR','NOT','IN','BETWEEN','LIKE','IS','NULL',
  'ORDER','BY','GROUP','HAVING','LIMIT','OFFSET','AS','JOIN','LEFT','RIGHT',
  'INNER','OUTER','CROSS','ON','USING','UNION','ALL','DISTINCT','EXISTS',
  'INSERT','INTO','VALUES','UPDATE','SET','DELETE','CREATE','TABLE','DROP',
  'ALTER','ADD','COLUMN','INDEX','VIEW','TRIGGER','BEGIN','COMMIT','ROLLBACK',
  'TRANSACTION','EXPLAIN','CASE','WHEN','THEN','ELSE','END','CAST',
  'ASC','DESC','PRIMARY','KEY','FOREIGN','REFERENCES','DEFAULT','CHECK',
  'UNIQUE','IF','RECURSIVE','WITH','EXCEPT','INTERSECT',
];

// ── SQLite ────────────────────────────────────────────────────────────────────

export const SQLITE_KEYWORDS = [
  ...COMMON_KEYWORDS,
  'PRAGMA','VACUUM','REINDEX','ATTACH','DETACH','REPLACE','ABORT','FAIL',
  'IGNORE','GLOB','REGEXP','ESCAPE','COLLATE','INDEXED','TEMP','TEMPORARY',
  'AUTOINCREMENT',
];

export const SQLITE_FUNCTIONS = [
  'COUNT','SUM','AVG','MIN','MAX','TOTAL','GROUP_CONCAT',
  'ABS','COALESCE','IFNULL','IIF','NULLIF','TYPEOF','LIKELIHOOD',
  'LENGTH','SUBSTR','SUBSTRING','UPPER','LOWER','TRIM','LTRIM','RTRIM',
  'REPLACE','INSTR','HEX','QUOTE','UNICODE','CHAR','PRINTF','FORMAT',
  'DATE','TIME','DATETIME','JULIANDAY','STRFTIME','UNIXEPOCH',
  'RANDOM','RANDOMBLOB','ZEROBLOB','LAST_INSERT_ROWID','CHANGES',
  'TOTAL_CHANGES','SQLITE_VERSION','ROUND','JSON','JSON_EXTRACT',
];

// ── PostgreSQL ────────────────────────────────────────────────────────────────

export const POSTGRES_KEYWORDS = [
  ...COMMON_KEYWORDS,
  'RETURNING','CONFLICT','NOTHING','DO','ON','ILIKE','SIMILAR','TO',
  'ARRAY','ANY','SOME','OVER','PARTITION','WINDOW','FILTER','WITHIN',
  'LATERAL','TABLESAMPLE','SYSTEM','BERNOULLI','ONLY','NATURAL',
  'FULL','CORRESPONDING','NOWAIT','SKIP','LOCKED','ROWS','RANGE',
  'UNBOUNDED','PRECEDING','FOLLOWING','CURRENT','ROW','TIES','FIRST',
  'LAST','NULLS','GENERATED','ALWAYS','IDENTITY','SEQUENCE','OWNED',
  'RESTART','INCREMENT','MAXVALUE','MINVALUE','CYCLE','SCHEMA','EXTENSION',
  'GRANT','REVOKE','PRIVILEGE','FUNCTION','PROCEDURE','LANGUAGE','RETURNS',
  'DECLARE','RAISE','NOTICE','EXCEPTION','BEGIN','LOOP','FOREACH',
  'TYPE','ENUM','DOMAIN','OPERATOR','AGGREGATE','CAST','COLLATION',
  'TABLESPACE','VACUUM','ANALYZE','CLUSTER','REINDEX','TRUNCATE','COPY',
];

export const POSTGRES_FUNCTIONS = [
  // Aggregate
  'COUNT','SUM','AVG','MIN','MAX','BOOL_AND','BOOL_OR','EVERY',
  'ARRAY_AGG','STRING_AGG','JSON_AGG','JSONB_AGG',
  // String
  'LENGTH','CHAR_LENGTH','OCTET_LENGTH','BIT_LENGTH',
  'UPPER','LOWER','INITCAP','TRIM','LTRIM','RTRIM','BTRIM',
  'LPAD','RPAD','REPLACE','REPEAT','REVERSE','SPLIT_PART',
  'SUBSTRING','LEFT','RIGHT','STRPOS','POSITION','OVERLAY',
  'FORMAT','CONCAT','CONCAT_WS','QUOTE_IDENT','QUOTE_LITERAL',
  'ENCODE','DECODE','MD5','SHA256','PG_ESCAPE_STRING',
  // Numeric
  'ABS','CEIL','CEILING','FLOOR','ROUND','TRUNC','SIGN','MOD','DIV',
  'POWER','SQRT','EXP','LN','LOG','RANDOM','SETSEED',
  'GREATEST','LEAST','COALESCE','NULLIF','NULLIFZERO',
  // Date/time
  'NOW','CURRENT_TIMESTAMP','CURRENT_DATE','CURRENT_TIME',
  'CLOCK_TIMESTAMP','STATEMENT_TIMESTAMP','TRANSACTION_TIMESTAMP',
  'AGE','DATE_PART','DATE_TRUNC','EXTRACT','MAKE_DATE','MAKE_TIME',
  'MAKE_TIMESTAMP','TO_DATE','TO_TIMESTAMP','TO_CHAR',
  // JSON
  'ROW_TO_JSON','TO_JSON','TO_JSONB','JSON_BUILD_OBJECT','JSON_BUILD_ARRAY',
  'JSONB_BUILD_OBJECT','JSONB_BUILD_ARRAY','JSON_OBJECT','JSON_ARRAY',
  'JSON_EXTRACT_PATH','JSONB_EXTRACT_PATH','JSON_EXTRACT_PATH_TEXT',
  // Window
  'ROW_NUMBER','RANK','DENSE_RANK','PERCENT_RANK','CUME_DIST',
  'NTILE','LAG','LEAD','FIRST_VALUE','LAST_VALUE','NTH_VALUE',
  // Type conversion
  'CAST','CONVERT','TO_NUMBER','TO_CHAR','PG_TYPEOF',
  // Utility
  'VERSION','PG_DATABASE_SIZE','PG_RELATION_SIZE','PG_TOTAL_RELATION_SIZE',
  'PG_SLEEP','GENERATE_SERIES','UNNEST','ARRAY','ARRAY_LENGTH',
];

// ── MySQL ─────────────────────────────────────────────────────────────────────

export const MYSQL_KEYWORDS = [
  ...COMMON_KEYWORDS,
  'SHOW','DESCRIBE','EXPLAIN','USE','DATABASES','TABLES','COLUMNS','STATUS',
  'LIKE','REGEXP','RLIKE','SOUNDS','BINARY','COLLATE','CHARSET','CHARACTER',
  'ENGINE','AUTO_INCREMENT','UNSIGNED','ZEROFILL','SIGNED','TINYINT','SMALLINT',
  'MEDIUMINT','BIGINT','FLOAT','DOUBLE','DECIMAL','NUMERIC','BIT','BOOLEAN',
  'DATE','DATETIME','TIMESTAMP','TIME','YEAR','CHAR','VARCHAR','TEXT',
  'TINYTEXT','MEDIUMTEXT','LONGTEXT','BLOB','TINYBLOB','MEDIUMBLOB','LONGBLOB',
  'ENUM','SET','JSON','GEOMETRY','POINT','LINESTRING','POLYGON',
  'OPTIMIZE','ANALYZE','CHECK','REPAIR','TRUNCATE','REPLACE','IGNORE',
  'STRAIGHT_JOIN','SQL_CALC_FOUND_ROWS','FOUND_ROWS','ROW_COUNT','LAST_INSERT_ID',
  'LOCK','UNLOCK','FLUSH','KILL','PROCESSLIST','VARIABLES','WARNINGS',
];

export const MYSQL_FUNCTIONS = [
  // Aggregate
  'COUNT','SUM','AVG','MIN','MAX','GROUP_CONCAT','BIT_AND','BIT_OR','BIT_XOR',
  'STD','STDDEV','STDDEV_POP','STDDEV_SAMP','VAR_POP','VAR_SAMP','VARIANCE',
  // String
  'LENGTH','CHAR_LENGTH','CHARACTER_LENGTH','BIT_LENGTH','OCTET_LENGTH',
  'UPPER','LOWER','UCASE','LCASE','TRIM','LTRIM','RTRIM',
  'LPAD','RPAD','REPLACE','REPEAT','REVERSE','SPACE',
  'SUBSTRING','SUBSTR','LEFT','RIGHT','MID','LOCATE','POSITION','INSTR',
  'FORMAT','CONCAT','CONCAT_WS','GROUP_CONCAT','QUOTE','ESCAPE',
  'HEX','UNHEX','BIN','OCT','CONV','ASCII','ORD','CHAR','ELT','FIELD',
  'FIND_IN_SET','MAKE_SET','LOAD_FILE','EXPORT_SET',
  'MD5','SHA','SHA1','SHA2','AES_ENCRYPT','AES_DECRYPT','ENCRYPT',
  // Numeric
  'ABS','CEIL','CEILING','FLOOR','ROUND','TRUNCATE','SIGN','MOD',
  'POW','POWER','SQRT','EXP','LN','LOG','LOG2','LOG10',
  'RAND','PI','RADIANS','DEGREES','SIN','COS','TAN','ASIN','ACOS','ATAN',
  'GREATEST','LEAST','COALESCE','NULLIF','IFNULL','IF','ISNULL',
  // Date/time
  'NOW','CURDATE','CURTIME','CURRENT_TIMESTAMP','CURRENT_DATE','CURRENT_TIME',
  'DATE','TIME','DATETIME','TIMESTAMP','YEAR','MONTH','DAY','HOUR','MINUTE','SECOND',
  'DAYOFWEEK','DAYOFMONTH','DAYOFYEAR','WEEKDAY','WEEK','QUARTER',
  'DATE_ADD','DATE_SUB','ADDDATE','SUBDATE','DATE_DIFF','DATEDIFF','TIMEDIFF',
  'DATE_FORMAT','TIME_FORMAT','STR_TO_DATE','EXTRACT','PERIOD_ADD','PERIOD_DIFF',
  'MAKEDATE','MAKETIME','SEC_TO_TIME','TIME_TO_SEC','UNIX_TIMESTAMP','FROM_UNIXTIME',
  // JSON
  'JSON_OBJECT','JSON_ARRAY','JSON_QUOTE','JSON_EXTRACT','JSON_UNQUOTE',
  'JSON_SET','JSON_INSERT','JSON_REPLACE','JSON_REMOVE','JSON_MERGE',
  'JSON_KEYS','JSON_VALUES','JSON_CONTAINS','JSON_TYPE','JSON_LENGTH',
  'JSON_ARRAY_APPEND','JSON_ARRAY_INSERT','JSON_DEPTH','JSON_SEARCH',
  // Window
  'ROW_NUMBER','RANK','DENSE_RANK','PERCENT_RANK','CUME_DIST','NTILE',
  'LAG','LEAD','FIRST_VALUE','LAST_VALUE','NTH_VALUE',
  // Utility
  'FOUND_ROWS','LAST_INSERT_ID','ROW_COUNT','VERSION','DATABASE','SCHEMA',
  'USER','CURRENT_USER','SESSION_USER','SYSTEM_USER','CONNECTION_ID',
  'BENCHMARK','SLEEP','UUID','UUID_SHORT',
];

// ── Dialect picker ────────────────────────────────────────────────────────────

export type DialectKind = 'sqlite' | 'postgres' | 'mysql' | string;

export interface DialectConstants {
  keywords: string[];
  functions: string[];
}

export function getDialectConstants(dialect: DialectKind): DialectConstants {
  switch (dialect) {
    case 'postgres': return { keywords: POSTGRES_KEYWORDS, functions: POSTGRES_FUNCTIONS };
    case 'mysql':    return { keywords: MYSQL_KEYWORDS,    functions: MYSQL_FUNCTIONS };
    default:         return { keywords: SQLITE_KEYWORDS,   functions: SQLITE_FUNCTIONS };
  }
}

// Legacy exports — kept for any code that still imports these names
export const SQL_KEYWORDS = SQLITE_KEYWORDS;
export const SQL_FUNCTIONS = SQLITE_FUNCTIONS;
